# PAIR PROGRAMMING MÓDULO 3
_________________________
## NUMPY

In [1]:
import numpy as np

### Creación e indexación.

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [2]:
array_uni = np.random.randint(10,100,50)
print(array_uni)

multiplos = array_uni[::5]
print(multiplos)

[16 22 19 78 47 18 19 92 42 64 17 99 49 53 37 90 93 94 15 79 40 25 68 83
 43 67 42 91 76 49 92 30 29 21 11 11 30 40 30 71 16 97 98 85 63 73 30 99
 76 33]
[16 18 17 90 40 67 92 11 16 73]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [3]:
array_uni_30 = np.random.randint(1,21,30)
print(array_uni_30)

impares = array_uni_30[1::2]
print(impares)

[ 2 14 10 17  1  3 16 20  7 15 19 15  1  7  4 13  1  6 12  3  6  6 11 15
 11  1 18 11 10 20]
[14 17  3 20 15 15  7 13  6  3  6 15  1 11 20]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [4]:
array_bi = np.random.rand(4, 6)
array_bi = np.round((array_bi*100),2)
array_bi

array([[ 1.29, 64.77, 19.81, 23.94, 11.03, 69.47],
       [71.84,  2.38, 26.31, 78.03, 78.28, 97.31],
       [18.91, 74.83, 78.85, 52.87, 48.8 , 87.09],
       [17.72, 76.36, 61.99,  9.07, 17.88, 88.89]])

4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [5]:
array_bi_2 = np.round(np.random.random_sample((6,4)),2)
print(array_bi_2)

columna = array_bi_2[:,1]
print(columna)

[[0.35 0.79 0.07 0.55]
 [0.17 0.42 0.7  0.47]
 [0.33 0.79 0.13 0.84]
 [0.69 0.46 0.7  0.64]
 [0.79 0.17 0.08 0.64]
 [0.79 0.96 0.76 0.49]]
[0.79 0.42 0.79 0.46 0.17 0.96]


5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [6]:
array30 = np.random.randint(-51,51,30)
print(f'{array30} \n')

negativos = array30[array30 <0]
print(f'{negativos} \n')

[ 42   1  42  -9 -12 -25 -40 -32  -6 -48 -47  39  21  23   5  46  14  -3
  24   2  32  -8  39  41   7 -26  -9 -27   0  39] 

[ -9 -12 -25 -40 -32  -6 -48 -47  -3  -8 -26  -9 -27] 



6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [7]:
array_uni_10 = np.round(np.random.rand(10),2)
print(f'{array_uni_10} \n')

elementos = np.where(array_uni_10 >0.5)
print(f'{elementos} \n')

[0.16 0.49 0.83 0.95 0.69 0.56 0.11 0.95 0.64 0.23] 

(array([2, 3, 4, 5, 7, 8]),) 



7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [8]:
array40 = np.random.randint(1,101,40)
print(f'{array40} \n')

elementos40 = array40[(array40 % 3 == 0) & (array40 % 4 == 0)]
print(f'{elementos40} \n')

[76 80  1 35 94 71 80 42 25 44 39 50 32  4  1 41 47 20 28 74 67 52  7 45
  1 95 89 78 91 86 84 78 74 82 48 72 49 86 64 23] 

[84 48 72] 



BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [9]:
array_tri = np.random.randint(0,101, (2,3,5))
print(f'{array_tri} \n')
print('------')

multiplos3 = np.where(array_tri % 3 == 0, 0, array_tri)
print(f'{multiplos3} \n')

[[[69 74 91 13  8]
  [22 61 62 98 60]
  [58 60  8 11 27]]

 [[29 89 58 92  0]
  [ 8 60 44 90 31]
  [36 30 90 41 54]]] 

------
[[[ 0 74 91 13  8]
  [22 61 62 98  0]
  [58  0  8 11  0]]

 [[29 89 58 92  0]
  [ 8  0 44  0 31]
  [ 0  0  0 41  0]]] 



### Reshape y transpose.

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [10]:
array_re = np.random.randint(1,101,(2,3,4))
print(f'{array_re} \n')
print('------------')

arraycambio = np.reshape(array_re,(6,4))
print(f'{arraycambio} \n')

[[[ 93  13  19  71]
  [ 41   2  44  60]
  [100  67   7  33]]

 [[ 51  14  68  40]
  [ 18  84  31  72]
  [ 33  22  16  50]]] 

------------
[[ 93  13  19  71]
 [ 41   2  44  60]
 [100  67   7  33]
 [ 51  14  68  40]
 [ 18  84  31  72]
 [ 33  22  16  50]] 



2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [ ]:
array3 = np.random.randint(1, 60, (3,4,5))
print(f'{array3} \n')
print('------------ \n')

arraycambio3 = np.reshape(array3,(12,5))
print(f'{arraycambio3} \n')
print('------------ \n')

arraycambio33 = np.reshape(arraycambio3, (5, 12))
print(f'{arraycambio33} \n')

3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [4]:
array4 = np.random.rand(4,3,2)
print(array4)
print('------------ \n')
nuevo_array4 = np.reshape(array4,(4,6))
print(nuevo_array4)

[[[0.10992502 0.90894385]
  [0.16794245 0.93668608]
  [0.23958282 0.72354739]]

 [[0.94759428 0.58811778]
  [0.77552827 0.99364801]
  [0.79142747 0.20182692]]

 [[0.8712442  0.38754523]
  [0.24942772 0.59108539]
  [0.64788152 0.03991777]]

 [[0.51686225 0.9108253 ]
  [0.57904215 0.81863501]
  [0.73880045 0.3889584 ]]]
------------ 

[[0.10992502 0.90894385 0.16794245 0.93668608 0.23958282 0.72354739]
 [0.94759428 0.58811778 0.77552827 0.99364801 0.79142747 0.20182692]
 [0.8712442  0.38754523 0.24942772 0.59108539 0.64788152 0.03991777]
 [0.51686225 0.9108253  0.57904215 0.81863501 0.73880045 0.3889584 ]]


4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [ ]:
print(array3)
print('-------- \n')

array3_permut = np.transpose(array3, (2,1,0))
print(array3_permut)

5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [7]:
nuevo_array4 = np.transpose(array4,(1,2,0))
print(nuevo_array4)

[[[0.10992502 0.94759428 0.8712442  0.51686225]
  [0.90894385 0.58811778 0.38754523 0.9108253 ]]

 [[0.16794245 0.77552827 0.24942772 0.57904215]
  [0.93668608 0.99364801 0.59108539 0.81863501]]

 [[0.23958282 0.79142747 0.64788152 0.73880045]
  [0.72354739 0.20182692 0.03991777 0.3889584 ]]]


### Funciones aritméticas y estadísticas

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.


In [12]:
arrayvacio = np.random.rand(2,3,5).round(1)
print(arrayvacio)

[[[0.2 0.1 0.  0.6 1. ]
  [0.  0.  0.9 0.6 0.9]
  [0.6 0.7 0.1 0.7 0.1]]

 [[0.5 0.7 0.6 0.1 0.5]
  [0.2 0.8 0.1 0.8 0. ]
  [0.8 0.3 0.5 0.7 0.7]]]


2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".


In [13]:
arrayvacio2 = np.round(np.random.rand(2,3,5),1)
print(f'{arrayvacio2}')

[[[0.3 0.1 0.2 0.5 0.5]
  [0.2 0.5 0.2 0.4 0.1]
  [0.5 0.9 0.8 0.5 0.4]]

 [[0.6 0.7 0.6 0.5 1. ]
  [0.6 0.1 0.4 0.3 0.1]
  [0.2 0.3 0.6 0.9 0.8]]]


In [14]:
igualmedia = np.where( arrayvacio2 == (np.mean(arrayvacio)), 'A', arrayvacio2)
print(f'{igualmedia} \n')
print('----------')

mayormedia = np.where( arrayvacio2 > (np.mean(arrayvacio)), 'B', arrayvacio2)
print(f'{mayormedia} \n')
print('----------')

menormedia = np.where( arrayvacio2 < (np.mean(arrayvacio)), 'C', arrayvacio2)
print(f'{menormedia} \n')
print('----------')

valormax = np.where( arrayvacio2 == (np.max(arrayvacio)), 'D', arrayvacio2)
print(f'{valormax} \n')
print('----------')

valormin = np.where( arrayvacio2 == (np.min(arrayvacio)), 'E', arrayvacio2)
print(f'{valormin} \n')

[[['0.3' '0.1' '0.2' '0.5' '0.5']
  ['0.2' '0.5' '0.2' '0.4' '0.1']
  ['0.5' '0.9' '0.8' '0.5' '0.4']]

 [['0.6' '0.7' '0.6' '0.5' '1.0']
  ['0.6' '0.1' '0.4' '0.3' '0.1']
  ['0.2' '0.3' '0.6' '0.9' '0.8']]] 

----------
[[['0.3' '0.1' '0.2' 'B' 'B']
  ['0.2' 'B' '0.2' '0.4' '0.1']
  ['B' 'B' 'B' 'B' '0.4']]

 [['B' 'B' 'B' 'B' 'B']
  ['B' '0.1' '0.4' '0.3' '0.1']
  ['0.2' '0.3' 'B' 'B' 'B']]] 

----------
[[['C' 'C' 'C' '0.5' '0.5']
  ['C' '0.5' 'C' 'C' 'C']
  ['0.5' '0.9' '0.8' '0.5' 'C']]

 [['0.6' '0.7' '0.6' '0.5' '1.0']
  ['0.6' 'C' 'C' 'C' 'C']
  ['C' 'C' '0.6' '0.9' '0.8']]] 

----------
[[['0.3' '0.1' '0.2' '0.5' '0.5']
  ['0.2' '0.5' '0.2' '0.4' '0.1']
  ['0.5' '0.9' '0.8' '0.5' '0.4']]

 [['0.6' '0.7' '0.6' '0.5' 'D']
  ['0.6' '0.1' '0.4' '0.3' '0.1']
  ['0.2' '0.3' '0.6' '0.9' '0.8']]] 

----------
[[['0.3' '0.1' '0.2' '0.5' '0.5']
  ['0.2' '0.5' '0.2' '0.4' '0.1']
  ['0.5' '0.9' '0.8' '0.5' '0.4']]

 [['0.6' '0.7' '0.6' '0.5' '1.0']
  ['0.6' '0.1' '0.4' '0.3' '0.1']
  ['0.